up:
	docker-compose up -d
	docker-compose -f docker-compose-mobile.yml up -d

down:
	docker-compose down
	docker-compose -f docker-compose-mobile.yml down

clean:
	rm -rf ./data
	mkdir ./data
	chmod 777 ./data