[Player]
  Index = 1
  PrivateKey = "{{ env `PLAYER1_PRIVATE_KEY` }}"
  
[Players.2]
  Address = "tsm-node2:9002?connectionPoolSize=6&connectionLifetime=5m"
  PublicKey = "{{ env `PLAYER2_PUBLIC_KEY` }}"

[Database]
    DriverName = "sqlite3"
    DataSourceName = "/data/tsm_node_1.sqlite"
    EncryptorMasterPassword = "encryptorMasterPassword1"

[MPCTCPServer]
  Port = 9001

[SDKServer]
  Port = 8001

[[Authentication.APIKeys]]
  APIKey = "1PebMT+BBvWvEIrZb/UWIi2/1aCrUvQwjksa0ddA3mA=" # apikey1
  ApplicationID = "demoapp"

[DKLS19]
