[Player]
  Index = 2
  PrivateKey = "{{ env `PLAYER2_PRIVATE_KEY` }}"

[Players.1]
  Address = "tsm-node1:9001?connectionPoolSize=6&connectionLifetime=5m"
  PublicKey = "{{ env `PLAYER1_PUBLIC_KEY` }}"

[Database]
    DriverName = "sqlite3"
    DataSourceName = "/data/tsm_node_2.sqlite"
    EncryptorMasterPassword = "encryptorMasterPassword2"

[MPCTCPServer]
  Port = 9002

[SDKServer]
  Port = 8002

[[Authentication.APIKeys]]
  APIKey = "FfrI+hyZAiVosAi53wewS0U1SsXKR0AEHZBM088rOeM="  # apikey2
  ApplicationID = "demoapp"

[DKLS19]